kind: ConfigMap
apiVersion: v1
metadata:
  name: codeflare-operator-config
data:
  config.yaml: |
    kuberay:
      rayDashboardOAuthEnabled: false
      ingressDomain: "kind"
      mTLSEnabled: false
