# Adds namespace to all resources.
namespace: openshift-operators

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/name: codeflare-operator
  app.kubernetes.io/part-of: codeflare

bases:
  - ../default
  - ../webhook

patches:
- path: manager_webhook_patch.yaml
- path: webhookcainjection_mpatch.yaml
- path: webhookcainjection_vpatch.yaml
