# This workflow will build the CodeFlare Operator dev image and push it to the project-codeflare image registry

name: Operator Dev Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'test/**'
      - '**.adoc'
      - '**.md'
      - 'LICENSE'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set Go
      uses: actions/setup-go@v5
      with:
        go-version: v1.20

    - name: Login to Quay.io
      id: podman-login-quay
      run: |
        podman login --username ${{ secrets.QUAY_ID }} --password ${{ secrets.QUAY_TOKEN }} quay.io

    - name: Image Build
      run: |
        make build
        make image-build -e IMG=quay.io/project-codeflare/codeflare-operator:dev
        make image-push -e IMG=quay.io/project-codeflare/codeflare-operator:dev

    - name: Logout from Quay.io
      if: always() && steps.podman-login-quay.outcome == 'success'
      run: |
        podman logout quay.io
