# This workflow will create a sync pr for the opendatahub-io/codeflare-operator fork with project-codeflare/codeflare-operator

name: Create Sync Fork PR

on:
  workflow_dispatch:

jobs:
  create-fork-sync-pr:
    runs-on: ubuntu-latest

    env:
      GIT_BRANCH: ${GITHUB_REF#refs/heads/}

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/opendatahub-io/codeflare-operator.git"
        source_branch: ${{ env.GIT_BRANCH }}
        destination_branch: "sync-cfo-fork"
        github_token: ${{ secrets.CODEFLARE_MACHINE_ACCOUNT_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.email "138894154+codeflare-machine-account@users.noreply.github.com"
        git config --global user.name "codeflare-machine-account"

    - name: Create Pull Request
      run: |
        PR_TITLE="Sync with Upstream"
        PR_BODY="This pull request updates the fork to match the latest changes from the upstream repository."
        gh pr create --base "${{ env.GIT_BRANCH }}" --head sync-cfo-fork --title "$PR_TITLE" --body "$PR_BODY"
      env:
        GITHUB_TOKEN: ${{ secrets.CODEFLARE_MACHINE_ACCOUNT_TOKEN }}
      shell: bash
